DROP DATABASE IF EXISTS ensf_614;
CREATE DATABASE ensf_614;
USE ensf_614;

DROP TABLE IF EXISTS USERTABLE;
CREATE TABLE USERTABLE(
    USERNAME    VARCHAR(25) NOT NULL,
    PASSWORD    VARCHAR(25) NOT NULL,
    PROFILE     VARCHAR(25) NOT NULL,
    EMAIL       VARCHAR(25) NOT NULL,
    DOB         TIMESTAMP,
    PRIMARY KEY (USERNAME)
);

DROP TABLE IF EXISTS FLIGHTS;
CREATE TABLE FLIGHTS (
    FLIGHTID        VARCHAR(25) NOT NULL,
    AIRCRAFTID      INT,
    SOURCE          VARCHAR(25) NOT NULL,
    DESTINATION     VARCHAR(25) NOT NULL,
    DEPARTURE       TIMESTAMP,
    LANDING         TIMESTAMP
);

DROP TABLE IF EXISTS REGISTEREDTICKETS;
CREATE TABLE REGISTEREDTICKETS (
    USERNAME        VARCHAR(25) NOT NULL,
    FLIGHTID        VARCHAR(25) NOT NULL,
    SEATNUMBER      VARCHAR(25) NOT NULL,
    PRIMARY KEY (FLIGHTID, SEATNUMBER)
);

DROP TABLE IF EXISTS CREW;
CREATE TABLE CREW (
    FNAME       VARCHAR(25) NOT NULL,
    LASTNAME    VARCHAR(25) NOT NULL,
    CREWID      VARCHAR(25) NOT NULL,
    PRIMARY KEY (CREWID)
);

DROP TABLE IF EXISTS ASSIGNEDCREW;
CREATE TABLE ASSIGNEDCREW (
    FLIGHTID    VARCHAR(25) NOT NULL,
    CREWID      VARCHAR(25) NOT NULL, -- Changed from INT to VARCHAR(25)
    PRIMARY KEY (FLIGHTID, CREWID)
);

DROP TABLE IF EXISTS AIRCRAFT;
CREATE TABLE AIRCRAFT (
    AIRCRAFTID  VARCHAR(25) NOT NULL,
    MODEL       VARCHAR(255) NOT NULL,
	PRIMARY KEY (AIRCRAFTID)
);


INSERT INTO USERTABLE (USERNAME, PASSWORD, PROFILE, EMAIL, DOB)
VALUES
('Braden', '1234', 'Agent', 'braden@gmail.com', '1996-10-17'),
('Fred', 'fred', 'Admin', 'fred@gmail.com', '1990-04-19'),
('Bob', 'bob', 'REGUSER', 'bob@gmail.com', '1999-09-12');

INSERT INTO FLIGHTS (FLIGHTID, AIRCRAFTID, SOURCE, DESTINATION, DEPARTURE, LANDING)
VALUES
('1','1', 'YYC', 'YVR', '2023-11-12', '2023-11-13'),
('2','1', 'YYC', 'YVR', '2023-11-12', '2023-11-14'),
('3','1', 'YYC', 'YVR', '2023-11-13', '2023-11-16');

INSERT INTO REGISTEREDTICKETS (USERNAME, FLIGHTID, SEATNUMBER)
VALUES
('Braden', '1', 'A1'),
('Guest', '1', 'B1'),
('Guest', '1', 'A3'),
('Guest', '1', 'C1'),
('Guest', '1', 'D4');

INSERT INTO CREW(FNAME, LASTNAME, CREWID)
VALUES
('Larry', 'Bird', '1'),
('Greg', 'Bird', '2'),
('Jon', 'Smith', '3'),
('Nancy', 'Drew', '4'),
('Bob', 'Tim', '5');

INSERT INTO ASSIGNEDCREW(FLIGHTID, CREWID)
VALUES
('1', '1'),
('1', '2');

INSERT INTO AIRCRAFT(AIRCRAFTID, MODEL)
VALUES
('1', 'A420'),
('2', 'A330');
